#config_version=5

# This defines our display.  New slides will automatically be placed
# here since this is the only display.
displays:
  window:
     width: 800
     height: 240

# This section defines some common widget settings so we don't
# duplicate them.
# 
# Read more about widget settings at the link below:
# http://docs.missionpinball.org/en/latest/displays/widgets/common_settings.html
widget_styles:
  segment_common:
    x: 0
    y: 200
    # 14 segment font used for displaying alphanumeric characters
    font_name: DSEG14Classic-Italic
    font_size: 60
    anchor_x: left
    anchor_y: top
    
widgets:
  display_text:
    - type: text
      # The DSEG14Classic-Italic font maps the exclamation point to a
      # blank space
      text: "PRESS!START!!!!!"
      color: orange
      style: segment_common
      z: 2
  unlit_segments:
    - type: text
      # The DSEG14Classic-Italic font maps the '~' character to the
      # 'all on' character
      text: "~~~~~~~~~~~~~~~~"
      # This widget is given a dark gray color so it's just barely visible
      color: 131313
      style: segment_common
      # The widget is given a lower z value because it needs to be
      # behind the display text
      z: 1
  
# This section defines a slide called 'press_start' and inserts the
# two widgets defined above into it
slides:
  press_start:
    widgets:
    - widget: display_text
    - widget: unlit_segments

# This section tells MPF to display our 'press_start' slide whenever
# the init_done event is fired.  In other words, when our game is done
# initializing, show our slide.
slide_player:
  init_done: press_start
    
